# GitHub Pages Configuration
title: backfeedr
description: Self-hosted crash reporting & app metrics for iOS indie developers
baseurl: "/backfeedr"
url: "https://steviee.github.io"

# Theme settings
remote_theme: just-the-docs/just-the-docs

# Color scheme
color_scheme: dark

# Navigation structure
nav_external_links:
  - title: GitHub
    url: https://github.com/steviee/backfeedr
    hide_icon: false

# Aux links (top right)
aux_links:
  "View on GitHub":
    - "//github.com/steviee/backfeedr"

# Footer content
footer_content: "Copyright 2026 Stephan E. Distributed under an MIT license."

# Search settings
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
